#!/usr/bin/perl

use FindBin;

my $bindir = $FindBin::Bin;

my $mrbs_dir = shift || ($ENV{HOME}.'/mrbs/mrbs_cvs/branch-1.2/mrbs');

if (! -d $mrbs_dir)
{
  die "MRBS sandbox not found, exitting\n";
}

chdir $mrbs_dir or die "Failed to change dir to sandbox\n";

(system($bindir.'/cvs2cl.pl','--usermap',$bindir.'/usermap-mrbs','--no-times',
        '--branches','--tags','--revisions','--utc','--ignore','ChangeLog',
        '--follow','mrbs-1_2-branch',) == 0) or die "Failed to run cvs2cl.pl\n";
